spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerledger
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /power-ledger
management:
  server:
    servlet:
      context-path: /actuator